<a href="https://colab.research.google.com/github/wcjona/BMEN_415_Final_Project/blob/main/Classification_Models/Classification_Models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# cleaning 
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

df = pd.read_csv("/content/Maternal Health Risk Data Set.csv")
df = df.drop_duplicates()
df = df.dropna()
df = df.replace({"low risk": 0, "mid risk":1, "high risk":2})
y = df["RiskLevel"]
x = df.loc[:,df.columns!="RiskLevel"]
mean_std_x=(x-x.mean())/x.std()
# Split training and test data
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=142)

Nearest Centroid

In [ ]:
from sklearn.neighbors import NearestCentroid
from sklearn.metrics import accuracy_score

model_NC = NearestCentroid()
model_NC.fit(x_train,y_train)

y_pred = model_NC.predict(x_test)
accuracy = accuracy_score(y_test,y_pred)
cm_nc = confusion_matrix(y_test,y_pred)

# Evaluate the models accuracy
print('Accuracy:',accuracy*100)
print('Confusion matrix',cm_nc)

Accuracy: 46.15384615384615
Confusion matrix [[26 10 16]
 [ 4  4 11]
 [ 7  1 12]]


Logistic Regression

In [ ]:
import numpy as np
from sklearn.linear_model import LogisticRegression

model_LR = LogisticRegression()

# Create the logistic regression model with higher iterations for testing as there was a convergence warning
model_LR = LogisticRegression(max_iter=1000)

model_LR.fit(x_train, y_train)

y_pred = model_LR.predict(x_test)

# Evaluate the model's accuracy
accuracy = accuracy_score(y_test,y_pred)
cm_lr = confusion_matrix(y_test,y_pred)
print('Accuracy', accuracy*100)
print('Confusion matrix',cm_lr)

Accuracy 75.82417582417582
Confusion matrix [[51  1  0]
 [11  5  3]
 [ 4  3 13]]


Quadratic Discriminant Analysis

In [ ]:
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

model_qda = QuadraticDiscriminantAnalysis()

model_qda.fit(x_train, y_train)

y_pred = model_qda.predict(x_test)

# Evaluate the models accuracy
Accuracy = model_qda.score(x_test, y_test)
cm_qda = confusion_matrix(y_test,y_pred)
print('Accuracy:',Accuracy*100)
print('Confusion matrix',cm_qda)

Accuracy: 75.82417582417582
Confusion matrix [[50  1  1]
 [11  6  2]
 [ 4  3 13]]
